---
  title: "Capstone Übung C.1: Javascript Basics"
---

> Wichtig: Bearbeiten Sie die Übungen **bevor** Sie sich die Lösungen ansehen.


## Aufgabe C.1.1

Erstellen Sie eine Schleife in Javascript, die die Zahlen von 10 bis 30 ausgibt.

[Lösung](loesungen/c-1-1.qmd)

## Aufgabe C.1.2

Gegeben ist der untenstehende String. Geben Sie mit Javascript die einzelnen Buchstaben des Strings in umgekehrter Reihenfolge _einzeln_ aus.
```text
Das Huhn frisst gerne Körner.
``` 

[Lösung](loesungen/c-1-2.qmd)

## Aufgabe C.1.3

Erstellen Sie eine Funktion mit dem Namen `subtract`, die als Parameter zwei Zahlen übergeben bekommt, die Zahl im zweiten Parameter von der Zahl im ersten Parameter subtrahiert und das Ergebnis dieser Subtraktion zurückgibt. Geben Sie einen Beispiel-Aufruf der Funktion an, der das Ergebnis ausgibt.

[Lösung](loesungen/c-1-3.qmd)

## Aufgabe C.1.4

Welche Ausgabe (Berechnung oder Fehler) erzeugt der folgende JavaScript-Code? Begründen Sie!
   
```javascript
console.log(weisnicht(3, weisnicht(2, 2, 11), 47))

function weisnicht(a, b, c) {
    return a * b
    console.log(a * a)    
}
```

[Lösung](loesungen/c-1-4.qmd)

## Aufgabe C.1.5
Gegeben ist der nachfolgende Code-Ausschnitt in Javascript. Erstellen Sie Code, der jeweils das Attribut `vorname` aller Objekte im Array data ausgibt. Der Code soll auch dann funktionieren, wenn weitere Objekte in das Array eingefügt werden. 

```javascript
const  data = [
    { nachname: "Karlsen", vorname: "Karl" },
    { nachname: "Klarsen", vorname: "Karla" }
]
```

[Lösung](loesungen/c-1-5.qmd)

## Aufgabe C.1.6
Schreiben Sie eine Arrow-Function, die zwei Zahlen entgegennimmt und die Summe der beiden Zahlen zurückgibt. Wenn Sonderfälle auftreten, behandeln Sie diese entsprechend.

[Lösung](loesungen/c-1-6.qmd)

## Aufgabe C.1.7
Schreiben Sie eine Schleife, die die Namen aus dem Array ausgibt und abbricht, sobald der Name Rebecca auftaucht. Dabei soll der name Rebecca noch ausgegeben werden. Der Code darf kein `if`-Statement enthalten.

```javascript
const namen = ['Malte', 'Svenja', 'Rebecca', 'Klaus'] 
```

[Lösung](loesungen/c-1-7.qmd)


## Aufgabe C.1.8
Erstellen Sie ein Objekt `auto`, das folgende Eigenschaften und Methoden enthält:

- **Eigenschaften:**
  - `marke` (z. B. "BMW")
  - `modell` (z. B. "X3")
  - `baujahr` (z. B. 2021)

- **Methoden:**
  1. `start()` → gibt `"Das Auto startet."` in der Konsole aus.  
  2. `info()` → gibt eine Beschreibung des Autos aus, z. B. `"BMW X3, Baujahr 2021"`.

Rufen Sie beide Methoden anschließend auf.

[Lösung](loesungen/c-1-8.qmd)


## Aufgabe C.1.9

Gegeben ist folgendes Objekt:

```javascript
const person = {
  vorname: "Lisa",
  nachname: "Meyer",
  alter: 28,
  beruf: "Webentwicklerin"
};
```

1. Verwenden Sie **Object Destructuring**, um die Werte der Eigenschaften `vorname` und `beruf` aus dem Objekt zu extrahieren.  
2. Geben Sie die Werte anschließend mit `console.log()` aus.  

[Lösung](loesungen/c-1-9.qmd)