---
  title: "Übung 8: AdonisJS Sessions"
---

## Aufgabe 1: Sichere Kundendaten
> Budget: 90 Minuten

Wir nehmen wieder unsere Kunden-Datenbank. In dieser Übung entsteht eine Passwort-geschütze Anwendung, in der die Kundendaten angezeigt werden können.

Unsere Schritte:
  
1. Erstellen Sie eine neue AdonisJS Anwendung an. Konfigurieren Sie entsprechend des Vorgehens aus der Vorlesung das Projekt, insbesondere die Datenbank-Verbindung.
2. Öffnen Sie die SQLite-Datenbank-Datei in einen geeigneten Werkzeug. Fügen Sie eine neue Tabelle `user` hinzu. Nutzer hat die Atriibute `login` und `password`. `login` ist der Login-Name. Da dieser eindeutig sein muss, ist das auch unser Primärschlüssen. _Beachten Sie, dass dieser natürlich in diesem Fall kein `autoincrement` ist_
3. Erstellen Sie eine `GET`-Route `/register`, die ein Registrierungsformular für neue Nutzer enthält, welches die Daten per `POST` an `/register` schickt.
4. Implementieren Sie die `POST`-Route `/register`, die die Daten in der Datenbank in der Tabelle `user` speichert. Passwörter werden natürlich grundsätzlich **gehasht** gespeichert.
5. Erstellen Sie eine `GET`-Route `/login`, die ein Login-Formular enthält, welches die Daten per `POST` an `/login` schickt.
6. Implementieren Sie die `POST`-Route `/login`, die die Daten aus dem Formular gegen die Datenbank prüft. Ist ein Login korrekt, speichern Sie den `login`-Namen in der Session.
7. Schützen Sie alle schützenswerten Routen, indem Sie prüfen ob das in der Session `login` enthalten ist. **Wichtig**: Nicht nur Formulare müssen geschützt werden, sondern viel wichtiger die zugehörigen `POST`-Routen. Warum ist das so?

## Homework Woche

Homework sind immer die Aufgaben bis zur kommenden Woche. Sie können natürlich schon beginnen, wenn Sie mit den anderen Aufgaben bereits fertig sind.

### Aufgabe 1: Verbesserte Anwendung
> Budget: 60 Minuten

Aktuell kann sich jeder regsitrieren. Das muss anders werden. Weg mit dem Registrierungsformular! Nur Administratoren können nach Login weitere Nutzer anlegen - und auch wieder löschen.

Erweitern Sie die Kundendaten-App entsprechend. Überlegen Sie sich, welche Seiten mit Formulare und Daten Sie benötigen. 